version: "3.8"
services:
    app:
        build: ./docker/php
        volumes:
            - ./laravel-project:/work
    
    web:
        image: nginx:1.18-alpine
        ports:
            - 8080:80
        volumes:
            - ./laravel-project:/work
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /work