FROM mysql/mysql-server:8.0

ENV MYSQL_DATABASE=laravel_local \
 MYSQL_USER=root \
  MYSQL_PASSWORD=root \
  MYSQL_ROOT_PASSWORD=root \
  TZ=Asia/Tokyo

  COPY ./my.cnf /etc/mysql/conf.d/my.cnf
  RUN chmod 644 /etc/mysql/conf.d/my.cnf